name: Deploy → Staging

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker build -t app-staging ./backend
      - name: Deploy
        run: echo "Agrega aquí tu comando de deploy"
        env:
          DEPLOY_TOKEN: ${{ secrets.STAGING_DEPLOY_TOKEN }}
